// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrEgF5v-_MuIZHOT2qnoc9_Svnw4kfQ6Q',
    appId: '1:962754751737:web:310d8d07c10de8f6250628',
    messagingSenderId: '962754751737',
    projectId: 'flightos-e9684',
    authDomain: 'flightos-e9684.firebaseapp.com',
    storageBucket: 'flightos-e9684.firebasestorage.app',
    measurementId: 'G-XSJJXDLVYG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByiJskd4FQ-sbae1xsI9IfcA8qGVdvyEc',
    appId: '1:962754751737:ios:6bf790acb59a0653250628',
    messagingSenderId: '962754751737',
    projectId: 'flightos-e9684',
    storageBucket: 'flightos-e9684.firebasestorage.app',
    iosClientId:
        '962754751737-53qp69fup5l9va7pqqd5ank1v3tdb4uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.skynav',
  );
}
